spring:
  application:
    name: login

server:
  port: 8080
  servlet:
    session:
      timeout: 3600 #세션 유지시간 설정
    encoding:
      force: true #mustache UTF-8
 
---
#mustache 설정
spring:
  mustache:
    cache: false
    servlet:
      expose-request-attributes: true #mustache에서 csrf 토큰 변수 오류 발생 때문에 추가
      expose-session-attributes: true #세션
 
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: [URL]
    username: [아이디]
    password: [비밀번호]
  jpa:
    properties:
      hibernate:
        format_sql: true #JPA 쿼리문 정렬된 형태로 출력
 
# JPA 쿼리문, binding parameter 출력
logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        orm:
          jdbc:
            bind: TRACE