spring:
  application:
    name: oauth2

server:
  port: 8080
  servlet:
    session:
      timeout: 3600 #세션 유지시간 설정
    encoding:
      force: true #mustache UTF-8
 
---
#mustache 설정
spring:
  mustache:
    cache: false
    servlet:
      expose-request-attributes: true #mustache에서 csrf 토큰 변수 오류 발생 때문에 추가
      expose-session-attributes: true #세션
 
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/work?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: user03
    password: localdbpass!
  jpa:
    properties:
      hibernate:
        format_sql: true #JPA 쿼리문 정렬된 형태로 출력
 
# JPA 쿼리문, binding parameter 출력
logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        orm:
          jdbc:
            bind: TRACE
            
---
#OAuth2 변수 설정
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [구글 클라이언트 ID]
            client-secret: [구글 클라이언트 보안 비밀번호]
            redirect-uri: [구글 리디렉션 URI]
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          naver:
            client-name: naver
            client-id: [네이버 Client ID]
            client-secret: [네이버 Client Secret]
            redirect-uri: [네이버 Callback URL]
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response